### PR TITLE
Multi tenant - Ready for Review

### PR DESCRIPTION
**Pull request by swstack**

### CODE REVIEW

**Comment by swstack** [comment]
@posborne @sbenhaim @funkyeah 

From what I can tell most of the functionality is complete in the multi-tenant branch.  All critical github issues have been addressed and closed (broken links, search, etc.).  Please checkout the branch, review the code, test stuff out.  If you find any bugs please create an issue and assign it to me.

Aesthetically we need to give some attention to /landing, /dashboard, /create ... I've given them a little bit of attention but they need some more.

**Comment by posborne** [comment]
You mean, this one wasn't good to merge @swstack

**Comment by swstack** [comment]
BOOM MERGED BITCH

**Comment by posborne** [comment]
> BOOM MERGED BITCH

Out of control.

**Pull request merged**
